import type { Metadata } from "next";
import { ClerkProvider, SignedIn, UserButton } from "@clerk/nextjs";
import { SignOutButton } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header className="flex justify-between items-center p-4 h-16 fixed w-full z-50">
            <SignedIn>
              <UserButton />
              <div className="bg-[#F4F4F5] py-2 px-2 rounded-2xl hover:opacity-35">
                <SignOutButton />
              </div>
            </SignedIn>
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}

{
  /* <div className="text-xl font-bold flex gap-2 items-center">
  <Coffee className="size-[20px]" />
  Buy Me Coffee
</div>
<div className="flex items-center gap-4 ">
  <SignedOut>
    <div className="border py-2 px-3 rounded-2xl bg-[#F4F4F5] hover:opacity-30">
      <SignInButton />
    </div>
    <div className="border py-2 px-3 rounded-2xl bg-[#F4F4F5] hover:opacity-30">
      <SignUpButton />
    </div>
  </SignedOut>
</div> */
}
